- code/game/objects/items/stacks/sheets/sheet_types.dm
- sandcode/code/modules/crafting/recipes/recipes_misc.dm
people may say it's op, but it's just good
:cl:
add: Metal tiny fan crafting
del: Crafting menu tiny fan
/:cl:
> Tiny fans on metal crafting (finally)

- sandcode/code/modules/hydroponics/grown/misc.dm
- tgstation.dme
Their boo varients, the names can be changed
> Adds atmos plants

- code/modules/clothing/spacesuits/hardsuit.dm
- sandcode/code/modules/mob/living/give.dm
> Ce hardsuit buff and give tweak

- code/controllers/configuration/entries/general.dm
- config/config.txt
- interface/interface.dm
- modular_citadel/interface/skin.dmf
Switches the forum button with something people will actually click
Attempt to bring more players, if they play once and don't join the discord, it's likely that they won't play again
:cl:
code: all instances of forum replaced with discord
config: FORUMURL replaced with DISCORDURL
/:cl:
> Replaces forum button with a discord button

- code/controllers/configuration/entries/game_options.dm
- code/modules/admin/verbs/randomverbs.dm
- code/modules/antagonists/nukeop/equipment/nuclearbomb.dm
- config/game_options.txt
Allows you to toggle that stupid message and it's only the inactive one, so nobody really gives a shit
Eventually the spam is just too much
:cl:
refactor: changed the code directly at the `admin_message` on loneop
config: added the option near to random events on `game_options.txt`
/:cl:
> Toggle disk msg

- code/modules/tgs/v4/api.dm
- code/modules/tgs/v5/api.dm
> [TESTMERGE] Dmapi

- code/controllers/subsystem/research.dm
- code/controllers/subsystem/shuttle.dm
Fixes the problem computer
You'd only do maths once and then the item would be useless for the rest of the round
:cl:
fix: adds some lines that i didn't see while doing the port.
/:cl:
AND DOES NOT DO IT IN UPSTREAM THIS TIME
> Problem computer fix

- _maps/map_files/BoxStation/BoxStation.dmm
- _maps/map_files/CogStation/CogStation.dmm
- _maps/map_files/Deltastation/DeltaStation2.dmm
- _maps/map_files/KiloStation/KiloStation.dmm
- _maps/map_files/LambdaStation/lambda.dmm
- _maps/map_files/MetaStation/MetaStation.dmm
- _maps/map_files/OmegaStation/OmegaStation.dmm
- _maps/map_files/PubbyStation/PubbyStation.dmm
- _maps/map_files/SmolStation/SmolStation.dmm
- _maps/map_files/Snaxi/Snaxi.dmm
- sandcode/code/game/machinery/cryopod.dm
- tgstation.dme
Adds centcom teleporters so you don't actually have to get frozen forever, just go home! Obviously prisoners can't go home and didn't get their cryos replaced.
I don't think it's nice for you to get frozen instead of just going home, also it's cool!
*Might be dangerous since it creates sparks*
:cl:
add: Replaced half cryos with teleporters
/:cl:
> CentCom Teleporters!

- code/modules/mob/mob.dm
- sandcode/code/interactions/lewd/lewd_datums.dm
Increases lewd interactions distance to 1, so you can actually do something to people right in front of you, also increased sprite shifting to 32, don't abuse it.
~~ERP~~ cozy casual rp.
:cl:
code: max_distance = 1
code: max pixel shifting set to 32.
/:cl:
> Quality of life thing?

- code/modules/research/designs/tool_designs.dm
Upstream merge
Update time
:cl:
/:cl:
> Upstream merge

- code/game/objects/items/stacks/sheets/sheet_types.dm
- code/modules/reagents/chemistry/reagents/medicine_reagents.dm
- code/modules/research/designs/nanite_designs.dm
- code/modules/research/nanites/extra_settings/number.dm
- code/modules/research/nanites/nanite_programs.dm
- code/modules/research/nanites/nanite_programs/sensor.dm
- code/modules/research/nanites/program_disks.dm
- sandcode/code/modules/research/nanites/nanite_programs/utility.dm
- sandcode/code/modules/research/techweb/all_nodes.dm
- tgstation.dme
Contains more stuff from all around!
Qols and fixes?
:cl:
add: Added nanite signaler. (Another-era)
tweak: Nanites can check your stamina level. (Another-era)
balance: Construction bags can be made just like the others! Though they cannot be researched anymore.
balance: Pentetic acid is more useful against walking chernobyl. (Another-era)
fix: Used Nanite fixes from another-era.
/:cl:
> Some useful stuff

- code/modules/mob/living/simple_animal/hostile/headcrab.dm
Headslugs back to the gold slime pool!
I guess it has no reason to be off here?
:cl:
tweak: Headslugs been re-added to gold slime spawn pool.
/:cl:
> Xenolings comeback

- sandcode/code/datums/mutations/combined.dm
- tgstation.dme
Re-allows being able to combine thermals with radioactive resulting in x-ray.
This has no reason in the entire universe to be removed.
:cl:
tweak: Re-adds genetics recipe (Thermal + Radioactive = X-ray)
/:cl:
> X-Ray mutation comeback

- code/modules/shuttle/navigation_computer.dm
- sandcode/code/modules/research/designs/machine_designs.dm
- sandcode/code/modules/research/techweb/all_nodes.dm
- sandcode/code/modules/shuttle/spaceship_navigation_beacon.dm
The thing is, i already had added them, though didn't do it properly and even if i did, we wouldn't have them.
Makes the spaceship beacons in the code usable *and the custom shuttles too since most of the time there would be no destination*.
:cl:
add: Spaceship beacon to the shuttle techweb.
fix: Spaceship beacon now works!
/:cl:
> Spaceship beacons and etc.

- sandcode/code/modules/client/loadout/__donator.dm
Fixes a certain item giving runtimes
No runtime good.
:cl:
fix: Fixes the evil loadout plushie runtiming.
/:cl:
> Fix loadout

- code/game/objects/structures/tables_racks.dm
Allows you to put your tools on the tables.
I DIDNT MEAN TO BREAK THE TABLE NOOOOOOOOOOOOO.
:cl:
refactor: By being on help intent, you can place screwdrivers and wrenchs on tables.
/:cl:
> Placing screwdrivers and wrenchs on tables

- code/controllers/configuration/entries/general.dm
- code/modules/admin/admin_verbs.dm
- code/modules/client/darkmode.dm
- interface/skin.dmf
- sandcode/code/modules/admin/verbs/fix_air.dm
- tgstation.dme
Air fixing is good, just as bugfixing.
Revert mistakes and fix the discord, how can we get peeps like that!
:cl:
add: Added a new admin command, "Fix air", choose a range and get breathable air!
fix: Fixed discord button being a forum button that does nothing.
/:cl:
> Adds tgstation's fix air for admins

- _maps/map_files/BoxStation/BoxStation.dmm
- _maps/map_files/SmolStation/SmolStation.dmm
> Fixing some stuff about maps.

- code/modules/admin/chat_commands.dm
- sandcode/code/modules/tgs/chat_commands.dm
- sandcode/code/modules/tgs/custom_procs.dm
- tgstation.dme
Some useful tgs changes.
Useful commands for the chat bot, cannot get denied.
:cl:
add: Adds !tgs who, for checking on the online players.
add: Adds !tgs awho, the "better" version of adminwho.
add: Adds !tgs restart, which should basically restart the server without having to join.
tweak: !tgs check should now display the current round time.
/:cl:
> [TESTMERGE] New tgs commands + modification of a existant one

- code/modules/admin/chat_commands.dm
Quick joins
Qol
:cl:
tweak: The ip that appears on `!tgs check` should be clickable now, allowing for a quick join.
/:cl:
> Make ip on check command clickable

- code/modules/client/preferences.dm
Move it.
Because you don't have to scroll for no reason while everything fits on a single screen.
:cl:
tweak: Moves Special Role settings to the middle, so you don't have to scroll down(also moved admins prefs to the right).
/:cl:
> Moves pref menu stuff again

- sandcode/code/modules/reagents/chemistry/recipes/others.dm
Allows the creation of anomalies through bluespace science chemistry!
It is indeed hard to get anomalies without random events, but this isn't bad either because it's costly/hard.
:cl:
add: Added chemistry reactions for anomalies.
/:cl:
> Artificially Created Anomalies

- code/datums/chatmessage.dm
Makes sure text is centralized above you.
Looks better than looking odd a bit to the left.
:cl:
fix: chaged the dogborg fix to be simpler + apply for all mobs.
/:cl:
> Runechat fix

- code/datums/ruins/lavaland.dm
Makes alien tech obtainable basically every round, considering there's a miner down there.
Allows progression for long rounds(literally all of them).
:cl:
tweak: It seems like abductors became more active, but they've been abducting robust people and there are ufo's crashing on lavaland frequently.
/:cl:
> Always spawn ufo ruin

- code/datums/chatmessage.dm
Reverts SandPoot/Sandstorm-Station-13#68
This messes up player positioning and has many quirks, somehow shifting your position on a tile affects other player's speech, HOW?
> Revert "Runechat fix"

- code/modules/mob/living/carbon/human/update_icons.dm
Title.
Broken is no good.
:cl:
fix: Fixes wrists overlay, you'll be able to see your stuff on your wrists now!
/:cl:
> Fixes a typo in wrists code

- config/config.txt
- config/game_options.txt
- config/sand/config.txt
- html/changelogs/SandPoot brute force copy.yml
Title.
It's for the best.
:cl:
config: Makes a separate config folder for sandstorm stuff.
/:cl:
> Separates Sandstorms configs from upstream.

- .github/workflows/make_changelogs.yml
Title.
WebhookProcessor is not helping a lot anymore.
:cl:
/:cl:
> Action changelogs

- sandcode/code/datums/mood_events/generic_negative_events.dm
- sandcode/code/game/objects/items/computermath.dm
- tgstation.dme
Title
That's a bit harsh... perhaps.
:cl:
tweak: The math computer no longer gives you brain damage and instead applies a negative mood.
/:cl:
> Math computer no more brain damage

- code/modules/client/preferences.dm
Title, also fixes the extreme harm button.
I am pretty sure people use their characters in multiple places, so being able to screen shoot it and know the color without Paint is actually good.
:cl:
tweak: "Change" color buttons on pref menu have been replaced by the selected color in hex.
fix: Fixes the extreme harm button.
/:cl:
> Replaces "change" buttons on the prefs menu with the selected color in hex.

- .github/PULL_REQUEST_TEMPLATE.md
It is now obligatory to state if it is a port or not, have fun.
Just for clearing up, and if anything breaks we can give a look at the original thing.
No.
No changelogs needed.
> Updates Pull Request Templates

- code/game/mecha/mech_fabricator.dm
- sandcode/code/modules/research/designs/mechfabricator_designs.dm
This isn't really a misc thing, surely needs it's own category.
No.
:cl:
add: Added the Power Armor category to the exosuit fabricators(mechfabs) and adds every part to it.
/:cl:
> Adds the Power Armor category for mech fabricators.

- sandcode/code/game/mecha/mecha_construction_paths.dm
Shows you all the steps to build mechs correctly.
*There's a downside, if new mechs or completely new steps get added their key needs to be updated because i doubt citadel will do it*
How build mech.
No.
:cl:
fix: All the mech's construction steps should be visible now when examining.
/:cl:
> Fixes mech's construction steps

- sandcode/code/modules/cargo/packs/vending.dm
- tgstation.dme
Title.
Why the bepis can we not buy those!?
No
:cl:
add: Added ClothesMate resupply canister to cargo for the same price of the AutoDrobe.
/:cl:
> ClothesMate Resupply Canisters Purchaseable

- sandcode/code/modules/research/designs/autolathe_designs/autolathe_designs_medical_and_dinnerware.dm
- tgstation.dme
Adds basic tanks to autolathes.
Not everything is obtainable, BUT SHOULD.
No
:cl:
tweak: Oxygen tank, plasma tank and emergency oxygen tanks can be made on the autolathe.
/:cl:
> Adds tanks to autolathe

- code/controllers/configuration/entries/game_options.dm
- code/controllers/subsystem/ticker.dm
- config/config.txt
- config/sandstorm/config.txt
- sandcode/code/controllers/configuration/entries/sandstorm.dm
- tgstation.dme
The server will ping a role on roundstart, it is set with `NEW_ROUND_PING`
This is useful
No
:cl:
add: Server will ping a role on roundstart (actual start) if set.
config: Changed configs location.
/:cl:
> Roundstart pings

- sandcode/code/game/objects/items/tools/crowbar.dm
- sandcode/code/game/objects/items/tools/screwdriver.dm
- sandcode/code/game/objects/items/tools/weldingtool.dm
- sandcode/code/game/objects/items/tools/wirecutters.dm
- sandcode/code/game/objects/items/tools/wrench.dm
Changes the icons on the makeshift tools to be the icons already made and saved to the codebase
Some actual style, and allows to differentiate between good and bad tools
No
:cl:
tweak: Icons for makeshift tools are all proper.
/:cl:
> Changes the icons on the makeshift tools

- sandcode/code/modules/mob/living/simple_animal/hostile/mining_mobs/imp.dm
adds leather and plasma ore to imp drops
Actually gives something for imps to give and adds an ability to obtain leather in Lavaland
NOPE
:cl:
add: leather to imp butcher drops
add: plasma ore to imp drops
/:cl:
> Imp butcher tweaks

- code/modules/unit_tests/character_saving.dm
title.
Yes, angry at travis.
No.
:cl:
fix: Fix unit testing.
/:cl:
> Fix unit testing

- sandcode/code/datums/components/riding.dm
- tgstation.dme
Title.
Good for borgs carrying someone, piggyback rides and everything that usually makes you ride someone, very good, speedmerge.
Yes, [Bobstation commit](https://gitlab.com/bobstation/bobstation/blob/afe4c5c72fc558e94dcf89241c4353d6bf0f8c0e/code/datums/components/riding.dm).
:cl:
tweak: Changing directions while carrying someone will make them turn too.
/:cl:
> Changing direction while carrying someone will make them change direction too.

- sandcode/code/modules/research/designs/tool_designs.dm
- sandcode/code/modules/research/techweb/all_nodes.dm
Title.
Makes sense and also 
No.
:cl:
tweak: The industrial welding tool is now available at industrial engineering tech.
/:cl:
> Adds the industrial welding tool to industrial engineering tech

- code/datums/chatmessage.dm
Fixes people without language speaking and borgs having their speech misplaced for others and vice-versa.
Old broken stuff fixed.
No.
:cl:
fix: Fixes people who do not know any language speaking.
fix: Fixes borgs having their speech misplaced for others and vice-versa.
/:cl:
> Fixes runechat

- code/game/world.dm
- code/modules/client/client_procs.dm
- config/sandstorm/config.txt
- modular_sand/code/controllers/configuration/entries/sandstorm.dm
Title.
Really no change.
No.
:cl:
config: Made a couple hardcoded stuff customizable.
server: Don't forget to change them at `config/sandstorm/config.txt`.
/:cl:
> Adding a couple changeable things for hosts

- code/modules/mob/living/simple_animal/friendly/farm_animals.dm
- modular_sand/code/modules/mob/living/simple_animal/friendly/farm_animals.dm
- tgstation.dme
Goats, when angered enter "combat mode", that is, they get the cool overlays and sounds but nothing else.
Goat.
No.
:cl:
tweak: Goats are visibly angry.
/:cl:
> "Goat combat mode"

- code/modules/flufftext/Dreaming.dm
Scared spessmans.
People have nightmares.
Yes, https://github.com/quotefox/Hyper-Station-13/commit/b955eb99911c454ee2e2c70ba06d292a946ec27a.
:cl:
add: You can now have nightmares, depends on your mood, though being under bedsheets(yes it stacks) makes it less likely for it to happen.
/:cl:
> Nightmares!

- code/__HELPERS/game.dm
- code/controllers/subsystem/job.dm
- code/datums/datacore.dm
- code/modules/client/preferences.dm
- code/modules/jobs/job_types/_job.dm
- code/modules/mob/dead/new_player/new_player.dm
- modular_citadel/code/modules/client/preferences_savefile.dm
- modular_sand/code/modules/jobs/job_types/_job.dm
- modular_sand/code/modules/jobs/job_types/_job_alt_titles.dm
- tgstation.dme
Adds in the possibility of choosing pre-defined alternative titles for jobs, You are announced as the alternative job, it's on your ID and it also shows up as the job on the late join menu. Introduced in such a way that it wouldn't impact the codeworkings of other stuff. Feel free to ask for more titles later.
Alternative jobs can be found on `modular_sand\code\modules\jobs\job_types\_job_alt_titles.dm`
Adds more flavor to choosing your job.
Yes, https://github.com/Skyrat-SS13/Skyrat13/pull/1887.
:cl:
add: Adds alternative titles for jobs.
/:cl:
> Alternative job titles

- modular_sand/code/game/machinery/cryptominers.dm
Allows the cryptomining machines to produce money for bank accounts that are not the cargo's budget.
Money
No.
:cl:
add: Adds the personal credit production for cryptomining machines. (produce money for yourself on your id)
spellcheck: Fixed a small thing on cryptomining deactivation, the symbol (*) already indicated that it is the machine, no need to say it's name again.
/:cl:
> Cryptomining machines producing money for other bank accounts

- modular_sand/code/datums/interactions/_interaction.dm
- modular_sand/code/datums/interactions/interaction_interface.dm
- modular_sand/code/datums/interactions/lewd/_lewd.dm
- modular_sand/code/datums/interactions/lewd/lewd_interactions.dm
- tgui/packages/tgui/interfaces/MobInteraction.js
The interactions are now tgui, we have peaked human performance.
Solve several bugs, unintended stuff, comments player unwanted behavior.
Absolutely not.
:cl:
add: Interactions now use tgui.
del: Old ui for interactions.
refactor: A bunch of small changes there so stuff doesn't break.
del: Comments out "do_fucking_animation"
fix: Self interactions only appear when openning the menu for yourself.
/:cl:
> TGUI's your interactions

- modular_sand/code/datums/interactions/_interaction.dm
- modular_sand/code/datums/interactions/interaction_interface.dm
- tgui/packages/tgui/interfaces/MobInteraction.js
Alright so, adds defines for clarity, deletes some comments that won't ever be used... makes ui_act not be shitcode, solves possible(?) edgecases of you not having the holder...
It is good.
No.
:cl:
refactor: Makes interaction code somewhat better.
/:cl:
> Some finishing touches at interactions

- modular_sand/code/datums/interactions/interaction_interface.dm
Interaction runs on the user who wishes to do the action *verbs are so weird*.
Fix
:cl:
fix: You can do interactions on mobs lacking a mind again.
/:cl:
> A major fix for interactions that can break it a lot

- code/modules/shuttle/custom_shuttle.dm
- modular_sand/code/modules/research/designs/misc_designs.dm
- modular_sand/code/modules/research/techweb/bluespace_nodes.dm
- modular_sand/code/modules/shuttle/custom_shuttle.dm
- modular_sand/code/modules/shuttle/shuttle_creation/shuttle_upgrades.dm
- tgstation.dme
Title, simply does not allow shuttles to throw everything around if upgraded.
You know when you have that enormous shuttle, with lots of items around that could potentially insta-crit someone if they get hit by all of them at the same time?
No.
:cl:
add: Adds a disk that allows custom shuttles to not throw stuff around.
add: Puts it on the same techweb of the Hyperlane Optimisation Upgrade.
/:cl:
> Smooth sailing

- code/game/machinery/computer/arcade.dm
- modular_sand/code/game/machinery/computer/arcade/tetris.dm
- modular_sand/code/modules/client/asset_cache.dm
Title, also adds it to the randomized arcades so you can get your fun roundstart.
Doesn't quite make sense to keep something in the game that doesn't work.
No.
:cl:
fix: Fixes T.E.T.R.I.S.
tweak: Random roundstart arcades have a chance to be T.E.T.R.I.S.
/:cl:
> Fixes T.E.T.R.I.S

- code/modules/research/xenobiology/xenobiology.dm
Title.
Good.
No.
:cl:
tweak: Everything(items) can be fireproofed using xenobiology's fireproofing potion.
/:cl:
> Allows fireproofing potion to be used on anything

- code/modules/mob/living/simple_animal/hostile/alien.dm
- modular_sand/code/modules/mob/living/simple_animal/hostile/alien.dm
- tgstation.dme
Title.
It's probably not.
No.
:cl:
tweak: All simple mob aliens give actual corpses on death allowing for organ retrieval.
/:cl:
> Simple mob aliens drop actual corpses

- modular_sand/code/game/machinery/cryptominers.dm
Title.
I never expected someone to shove their pda into the machine which is expecting an id, result: runtimes.
So i guess now you can just shove your pda... tablet and what-not as well to put your account into it (obviously the id must be inside).
:cl:
feature: Pdas, tablet and stuff like that can be used to put your account into cryptomining machines.
fix: Fixes cryptomining machines runtiming when you shove something like a pda into it.
/:cl:
> Fix cryptominers

- modular_sand/code/modules/mob/emote.dm
Title, i really don't know how it breaks, weren't deleted stuff meant to be gone?
Fix.
No.
:cl:
fix: Fixed having infinite deleted vis_contents resulting in bad runtimes.
/:cl:
> Fixes vis_contents being filled with the combat mode flicks

- code/modules/unit_tests/_unit_tests.dm
- code/modules/unit_tests/interactions.dm
- modular_sand/code/datums/interactions/_interaction.dm
- modular_sand/code/datums/interactions/interaction_definitions.dm
- modular_sand/code/datums/interactions/interaction_interface.dm
- modular_sand/code/datums/interactions/interaction_mob.dm
- modular_sand/code/datums/interactions/lewd/_lewd.dm
- modular_sand/code/datums/interactions/lewd/lewd_datums.dm
- modular_sand/code/datums/interactions/lewd/lewd_datums_extra.dm
- modular_sand/code/datums/interactions/lewd/lewd_interactions.dm
- modular_sand/code/datums/interactions/lewd/objects.dm
- tgui/packages/tgui/interfaces/MobInteraction.js
Title.
It really is.
No.
:cl:
del: Removed some old bad code and commented things.
refactor: A lot of improvement to interaction code.
/:cl:
> Updates Interactions

- modular_sand/code/modules/reagents/reagent_containers/dropper.dm
- modular_sand/code/modules/research/designs/misc_designs.dm
- modular_sand/code/modules/research/techweb/all_nodes.dm
- tgstation.dme
Title.
You can only buy more at cargo, go make some yourself with plastic.
No.
:cl:
add: Added droppers to autolathes and protolathes.
/:cl:
> Adds droppers to autolathes and protolathes

- code/modules/surgery/organ_manipulation.dm
Title, nothing else.
Allows you to see what you're touching and felt nice.
No.
:cl:
tweak: Organ manipulation surgery now shows the organs in a radial wheel for better manipulation.
/:cl:
> Organ manipulation uses radial wheels

- code/datums/components/mood.dm
- code/game/objects/items/devices/scanners.dm
- code/modules/antagonists/clockcult/clock_mobs.dm
- code/modules/antagonists/devil/true_devil/_true_devil.dm
- code/modules/hydroponics/grown.dm
- code/modules/hydroponics/growninedible.dm
- code/modules/hydroponics/hydroponics.dm
- code/modules/hydroponics/sample.dm
- code/modules/hydroponics/seeds.dm
- code/modules/integrated_electronics/core/assemblies.dm
- code/modules/mob/living/carbon/carbon_defense.dm
- code/modules/mob/living/carbon/examine.dm
- code/modules/mob/living/carbon/human/examine.dm
- code/modules/mob/living/carbon/human/human_defense.dm
- code/modules/mob/living/carbon/human/login.dm
- code/modules/mob/living/silicon/ai/examine.dm
- code/modules/mob/living/silicon/robot/examine.dm
- code/modules/mob/living/simple_animal/constructs.dm
- code/modules/mob/living/simple_animal/friendly/drone/_drone.dm
- code/modules/mob/living/simple_animal/guardian/types/dextrous.dm
- code/modules/mob/living/simple_animal/slime/slime.dm
- interface/stylesheet.dm
- tgui/packages/tgui-panel/chat/constants.js
- tgui/packages/tgui-panel/styles/goon/chat-dark.scss
- tgui/packages/tgui-panel/styles/goon/chat-light.scss
Puts those boxes in a lot of places, mostly the places where there's \*-----* to separate texts.
It looks good and was intended to be added earlier, thanks for the help.
It looks like this:
Yes, [Septic Shock commit 064df0c736b587c85c7df92df6e1064e136d5cc9](https://gitgud.io/bobstation/bobstation-reignited/-/commit/064df0c736b587c85c7df92df6e1064e136d5cc9)
:cl:
tweak: Puts infoboxes in a bunch of useful places.
fix: Repairing circuitry will not to_chat(world) anymore, thanks hippiestation.
/:cl:
> Adds infoboxes

- code/modules/arousal/genitals.dm
- modular_sand/code/datums/interactions/interaction_interface.dm
- tgui/packages/tgui/interfaces/MobInteraction.js
Title!
Adds a couple of useful functions to the interaction menu, including genital visibility toggles, character prefs, and erp prefs.
No.
:cl:
add: The interaction menu got tabs with a lot of new features, go check it out!
/:cl:
> Adds tabs to the interaction menu

- code/datums/datacore.dm
- code/game/data_huds.dm
- code/game/machinery/porta_turret/portable_turret.dm
- code/game/objects/items/cards_ids.dm
- code/modules/jobs/access.dm
Title.
It is.
No.
:cl:
fix: Attempts solving some issues with alt titles by having checks go for the actual job name, and not the alt title.
/:cl:
> Tries to make it so alt titles aren't just a challenge and broken

- code/datums/elements/flavor_text.dm
- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/silicon/silicon.dm
Title.
Makes some awful stuff good.
No.
:cl:
tweak: Makes it so ooc notes always appear (just so people can see your erp prefs) even if empty, the only exception is having your face covered.
fix: You should no longer always see people's flavor texts (if they were visible) while they are masked or something, didn't really notice anything before but just to make sure.
/:cl:
> Fixes flavor text

- modular_sand/code/game/mecha/mecha.dm
- tgstation.dme
Mechs don't actually feel scary or anything and they're the size of any human.
Big mechs
No.
:cl:
tweak: Mechs look big, no gameplay differences however.
/:cl:
> Resizes mechs to be 1.5 of their regular size

- code/modules/arousal/arousal.dm
- modular_sand/code/datums/interactions/lewd/_lewd.dm
- modular_sand/code/datums/interactions/lewd/_lewd_extra.dm
- modular_sand/code/datums/interactions/lewd/lewd_datums.dm
- modular_sand/code/datums/interactions/lewd/lewd_datums_extra.dm
- modular_sand/code/datums/interactions/lewd/lewd_interactions.dm
- modular_sand/code/datums/interactions/lewd/lewd_species.dm
- modular_sand/code/game/objects/items/fleshlight.dm
Title.
FIxes stuff and all that.
No.
:cl:
add: You can know the size of your portallight partner (receiver end)
add: Frotting.
fix: You actually get to know when your partner came with the portallight!
/:cl:
> Updates some lewd stuff

- code/modules/integrated_electronics/core/debugger.dm
- code/modules/integrated_electronics/subtypes/access.dm
- code/modules/integrated_electronics/subtypes/input.dm
- code/modules/integrated_electronics/subtypes/manipulation.dm
- code/modules/integrated_electronics/subtypes/smart.dm
Title.
No more confusion, also put some work into it, a boring card reader that instantly gives it all of your access? boo.
No.
:cl:
tweak: Circuitry is more consistent with it's access, use passkey.
fix: The harvesting mode of the plant circuit will actually output a list of harvests.
/:cl:
> Kills off the weird new access system for circuitry, give em passkeys.

- code/modules/client/preferences.dm
- modular_citadel/code/modules/client/preferences_savefile.dm
- modular_sand/code/datums/interactions/_interaction.dm
- modular_sand/code/datums/interactions/lewd/_lewd.dm
- modular_sand/code/datums/interactions/lewd/lewd_datums_extra.dm
Title.
Yes.
No.
:cl:
add: Lust tolerance and sexual potency are now prefs.
tweak: No more refractory period.
fix: Fixes some stuff with self interactions.
sounddel: No more loud slapping on frotting.
/:cl:
> Updates some lewd stuff again

- code/modules/client/preferences.dm
Title.
You currently cannot pick white, but if you pick black it makes white????
No.
:cl:
fix: Picking speech color should make sense now.
/:cl:
> Makes the dark color checker for speech color better

- code/modules/hydroponics/hydroponics.dm
- code/modules/integrated_electronics/subtypes/manipulation.dm
- modular_sand/code/modules/hydroponics/hydroponics.dm
- tgstation.dme
Title.
It's a fix, i can't believe `harvest_dead` is not a proc yet.
No.
:cl:
fix: Fixes hydro duplication glitch.
/:cl:
> Fixes circuit harvesting

- modular_sand/code/modules/clothing/gloves/accessories.dm
If you're reading this I'll suck your cock(s)
It fixes a lot of runtimes happening because of procs and vars rings don't have
I fucking HATE lag spikes
No
:cl:
fix: fixes some ring related runtimes
/:cl:
> Fixes rings errors

- code/modules/mob/living/simple_animal/bot/cleanbot.dm
Title
should've been on the climax revamp pull but I forgor
I guess?
:cl:
tweak: cleanbot now cleans semendrips
/:cl:
> Cleanbot cleans semendrips now

- code/game/objects/effects/decals/cleanable.dm
- code/game/objects/effects/decals/cleanable/humans.dm
- code/modules/antagonists/cult/blood_magic.dm
- code/modules/mob/living/carbon/human/human_movement.dm
checking if it's the correct type should be done for all procs that require shoes to be of type /obj/item/clothing/shoes
Fixes procs asking for a hat item's bloody shoes, there may be more procs that do stuff like this in different ways around the code though
Not a big fan of crashes
No
:cl:
fix: fixed crashing runtimes in the bloody shoes procs with the new size system
/:cl:
> Fixes some of the new size system's runtimes

- modular_sand/code/modules/mob/living/living_movement.dm
- tgstation.dme
Title, you can now change your layer to appear under or above someone else.
Erp, seriously.
Yes, https://github.com/Skyrat-SS13/Skyrat-tg/pull/1943.
:cl: NotRanged
add: Added two verbs to the IC tab that change your mob's 'layer' (sprite background/foreground priority) slightly.
/:cl:
> Layer changing verbs

- modular_sand/code/datums/interactions/lewd/_lewd.dm
Now they use actual prons instead of they/them. Tell me if I missed or miscalled any
i wondered why these weren't formatted
no
:cl:
tweak: now old interactions use the pronoun procs
/:cl:
> Upgraded interactions (kinda)

- modular_sand/code/modules/clothing/suits/miscellaneous.dm
Title.
Non-invisible clothing.
No.
:cl:
fix: The Oilskin Duster is now visible.
/:cl:
> Fixes the duster

- code/modules/balloon_alert/balloon_alert.dm
- modular_sand/code/datums/elements/holder_micro.dm
- modular_sand/code/game/atoms.dm
- modular_sand/code/game/machinery/cryptominers.dm
- modular_sand/code/game/objects/items/cosmetics.dm
- modular_sand/code/game/objects/items/devices/extra_arm.dm
- modular_sand/code/game/turfs/open.dm
- modular_sand/code/game/turfs/simulated/floor/plating.dm
- modular_sand/code/modules/mining/machine_bluespaceminer.dm
- modular_sand/code/modules/mob/living/simple_animal/bot/hugbot.dm
- modular_sand/code/modules/telescience/telesci_computer.dm
- tgstation.dme
Title.
Good code and quick alerts.
No.
:cl:
tweak: A bunch of different sandstorm content has been modified to use balloon_alert().
fix: Turfs can have balloon alerts.
/:cl:
> Makes a bunch of our stuff use balloon_alert()

- modular_sand/code/modules/reagents/chemistry/reagents/cit_reagents.dm
The file in modular_sand created a nonexistant fluid
misinput
No
:cl:
bugfix: Fixes femcum hydratation
/:cl:
> Fixes femcum hydratation

- code/__DEFINES/sandcode/chat.dm
- code/datums/components/mood.dm
- code/game/atoms.dm
- code/game/objects/items/devices/scanners.dm
- code/modules/antagonists/clockcult/clock_mobs.dm
- code/modules/antagonists/devil/true_devil/_true_devil.dm
- code/modules/hydroponics/grown.dm
- code/modules/hydroponics/growninedible.dm
- code/modules/hydroponics/hydroponics.dm
- code/modules/hydroponics/seeds.dm
- code/modules/mob/living/carbon/carbon_defense.dm
- code/modules/mob/living/carbon/examine.dm
- code/modules/mob/living/carbon/human/examine.dm
- code/modules/mob/living/carbon/human/human_defense.dm
- code/modules/mob/living/carbon/human/login.dm
- code/modules/mob/living/silicon/ai/examine.dm
- code/modules/mob/living/silicon/robot/examine.dm
- code/modules/mob/living/simple_animal/constructs.dm
- code/modules/mob/living/simple_animal/friendly/drone/_drone.dm
- code/modules/mob/living/simple_animal/guardian/types/dextrous.dm
- code/modules/mob/living/simple_animal/slime/slime.dm
- code/modules/mob/mob.dm
- interface/stylesheet.dm
- tgstation.dme
- tgui/packages/tgui-panel/chat/constants.js
- tgui/packages/tgui-panel/styles/goon/chat-dark.scss
- tgui/packages/tgui-panel/styles/goon/chat-light.scss
You may remember those from skyrat, now they're here.
Stylish.
[Yes, it's somewhere around here, they've made a mess.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8153)
:cl:
add: Examine blocks.
refactor: Replaced all infoboxes with it.
/:cl:
> Replaces infoboxes with examine blocks

- code/modules/cargo/packs/misc.dm
- code/modules/uplink/uplink_items/uplink_bundles.dm
- modular_sand/code/modules/cargo/packs/emergency.dm
- modular_sand/code/modules/cargo/packs/misc.dm
- modular_sand/code/modules/cargo/packs/supply_pack.dm
- tgstation.dme
Basically fixes uplinks, nullcrates, etc...
CItadel broke something important and didn't notice.
No.
:cl:
fix: Fixes any sort of crate related syndicate item fetching.
/:cl:
> Fixes uplink items fetching

- modular_sand/code/modules/cargo/blackmarket/blackmarket_items/clothing.dm
- modular_sand/code/modules/cargo/blackmarket/blackmarket_items/gadgets.dm
- modular_sand/code/modules/cargo/blackmarket/blackmarket_items/misc.dm
- modular_sand/code/modules/cargo/blackmarket/blackmarket_items/weapons.dm
- modular_sand/code/modules/cargo/packs/emergency.dm
Title.
Pushes ***SPECIAL*** stuff's costs up.
No.
:cl:
balance: Some blackmarket items and the null crate have gotten their prices go up from demand.
/:cl:
> Rebalance Prices

- modular_sand/code/modules/mining/machine_bluespaceminer.dm
Title.
Fixes stuff and all, good point.
No.
:cl:
qol: It is now very noticeable when the bluespace miner cannot mine.
balance: Bluespace miners cannot mine whilst unanchored, as god intended.
fix: Tools won't behave weirdly on the bluespace miner, and you can now unanchor it.
code: Made bluespace miner code less shit.
/:cl:
> Does some fine tweaks on the bluespace miner, no real major changes yet.

- modular_sand/code/datums/interactions/lewd/interactions/breasts.dm
- modular_sand/code/datums/interactions/lewd/interactions/self/breasts.dm
This makes it so the interactions actually use the name of the fluid instead of their path
datum paths don't look very good
No
:cl:
fix: fixes breastfeeding interactions
/:cl:
> Breastfeeding broke

- modular_sand/code/datums/interactions/lewd/_lewd.dm
Title.
I hate this pr section.
No.
:cl:
fix: Mobs lacking the vars in GLOB.slots won't create infinite runtimes anymore.
/:cl:
> Fixes an immense amount of runtimes.

- code/modules/client/preferences_savefile.dm
One line of code made silicon flavor text not save for over two years. How it was never noticed is one of life's wonders
No
:cl:
fix: Fixes silicon flavor text so it properly saves and loads through rounds
/:cl:
> Fixes silicon flavor text

- code/__SANDCODE/DEFINES/dcs/signals/sizecode.dm
- code/datums/dna.dm
- code/modules/client/preferences.dm
- modular_sand/code/datums/elements/holder_micro.dm
- modular_sand/code/modules/mob/living/living.dm
Title.
Fixes.
No.
:cl:
fix: `mob_size` is no longer weird
balance: After resizing and being on a mob's hand you will be dropped as they are not able to carry someone bigger than half your size.
/:cl:
> Fixing some stuff about sizecode

- code/game/machinery/computer/dna_console.dm
- code/game/objects/items/dna_injector.dm
- tgui/packages/tgui/interfaces/DnaConsole.js
This is a port of crispr from tg, for more info look at the PORT section.
More gaming opportunities.
Yes, https://github.com/tgstation/tgstation/pull/53173.
:cl:
add: Adds CRISPR - a gene editing method that lets you overwrite base mutations
/:cl:
> CRISPR for Base Gene editing

- modular_sand/code/modules/jobs/job_types/_job_alt_titles.dm
Adds a single and new job title for the assistant role
More possibilities for roleplay
No
:cl:
add: Added new assistant title
/:cl:
> Adds Off-Duty title

- modular_sand/code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
- tgstation.dme
Allows lizards to pick ears.
Muh flavor.
Negative.
:cl:
tweak: Lizards can now have ears... external ones that is.
/:cl:
> Lets lizards have ears

- code/controllers/subsystem/job.dm
- modular_citadel/code/modules/custom_loadout/load_to_mob.dm
Fixes it.
Why the fuck would you keep this shit in the game if it does nothing
No.
:cl:
fix: Fixed custom_roundstart_items, go reward your favorite players.
/:cl:
> Fixes custom roundstart items

- code/modules/mob/living/carbon/human/species_types/dwarves.dm
For whatever reason the last time i fixed this there was apparently a signal meant to be called when the person was no longer a dwarf, issue, it started being called some other time but fucking nobody is actually capable of speech. 
Fix.
:cl:
fix: Fixed dwarves (again) thanks for the bug supporters: None.
/:cl:
> Fixes dwarves (again)

- modular_sand/code/game/machinery/cryptominers.dm
This PR does the following things
- Reduces redundancy
- Prevents the space-turf exploit
- Heats air instead of spawning it
Improved code, less exploitable, and less atmos lag.
No.
:cl:
tweak: Cryptominer no longer functions in space
tweak: Cryptominer no longer produces Co2
code: Refactored processing for cryptominer
/:cl:
> Refactor cryptominer processing

- modular_sand/code/datums/interactions/interaction_interface.dm
- modular_sand/code/datums/interactions/lewd_definitions.dm
- modular_sand/code/modules/arousal/genitals.dm
- tgstation.dme
- tgui/packages/tgui/interfaces/MobInteraction.tsx
Title.
Lewd.
:cl:
add: You can now allow interacting with your genitals through clothes.
/:cl:
> Adds a button to toggle the capability of interacting through clothes

- code/__HELPERS/_cit_helpers.dm
- modular_sand/code/datums/interactions/lewd_definitions.dm
optimizes some genital procs to make them use less space while still defining the original ones to avoid having to replace each and every instance of them. Also makes the butt proc fit the code more properly
lets not copypaste
No
:cl:
code: optimizes some genital related code
/:cl:
> optimized some copypasted code

- code/__DEFINES/loadout.dm
- code/__SANDCODE/DEFINES/DNA.dm
- code/__SANDCODE/DEFINES/loadout.dm
- code/_onclick/hud/new_player.dm
- code/modules/client/preferences.dm
- code/modules/mob/dead/new_player/preferences_setup.dm
- tgstation.dme
Overhauls the preferences menu, HARD.
Puts things in logical senses, easier to find (maybe) and just generally appealing to the eye.
Yes, it is from [Skyrat#675](https://github.com/Skyrat-SS13/Skyrat-tg/pull/675)
:cl:
qol: The preferences UI has been totally clawed, enjoy.
/:cl:
> Re-UI-ing (just steals old skyrat)

- code/_onclick/click.dm
- code/modules/mob/mob.dm
Title.
Points at you.
:cl:
tweak: Pointing will make the arrow face it and you can also pixel-perfect point.
/:cl:
> Pointing at something will rotate the arrow and you can pixel-perfect point

- modular_sand/code/modules/jobs/job_types/_job_alt_titles.dm
Adds new Alt Titles for the HOS, Doctor, Paramedic, Roboticist, and Geneticist roles.
More Alt Titles are always good for RP. The AEMT and Field Surgeon titles could provide some good opportunities for character/character interactions.
Partially
:cl: Arrhythmia_V
add: Added Tarkhan HOS Alt Title
add: Added Emergency Physician Doctor Alt Title
add: Added Field Surgeon Doctor Alt Title
add: Added Bioengineer Geneticist Alt Title
add: Added Advanced Emergency Medical Technician Paramedic Alt Title
add: Ports MODsuit Engineer Roboticist Alt Title
/:cl:
> Adds New Alt Titles

- modular_sand/code/datums/interactions/interaction_datums/lewd/breasts.dm
- modular_sand/code/datums/interactions/interaction_datums/lewd/finger.dm
- modular_sand/code/datums/interactions/interaction_datums/lewd/handjob.dm
- modular_sand/code/datums/interactions/interaction_datums/lewd/self/jack.dm
- modular_sand/code/datums/interactions/lewd_definitions.dm
Title, you can now also milk other people.
Probably should've done this at the first pr.
No.
:cl:
add: You can milk other people using the interaction menu.
/:cl:
> Interactions: milking others

- modular_sand/code/datums/elements/holder_micro.dm
Title.
This is funny.
No.
:cl:
tweak: Carrying small people in your active hand allows you to use their access for airlocks/etc.
/:cl:
> You can use small people's access by holding them in your hand, like you would a wallet or others.

- code/controllers/subsystem/vote.dm
Harms lowpop servers, does nothing for highpop servers, i hate you..
No.
:cl:
del: There is no longer a minimum vote amount for extending rounds.
/:cl:
> Removes poorly designed hardcoded transfer vote system

- modular_sand/code/game/machinery/autodoc.dm
Title.
Deals with some bad practices and deploys fixes.
No.
:cl:
fix: The autodoc can no longer be spammed to apply multiple implants at once.
refactor: Refactored some autodoc code.
qol: You can leave the autodoc like a closet (by moving or resisting).
qol: The occupant on an autodoc can see the progress of the operation.
qol: The time required for a surgery is visible upon examination.
balance: You need to get close to see any information about the machine.
/:cl:
> Updates autodoc code (the machine)

- code/__SANDCODE/DEFINES/dcs/signals/lewd.dm
- modular_sand/code/datums/interactions/lewd_definitions.dm
- tgstation.dme
Title.
Could be used in several different cases in the future.
Yes, https://github.com/SPLURT-Station/S.P.L.U.R.T-Station-13/pull/135, only the signal has been implemented.
:cl:
code: Adds signals for sex to be used by coders in the future.
/:cl:
> Adds signals to cumming

- code/modules/client/preferences.dm
- code/modules/client/preferences_savefile.dm
- modular_sand/code/modules/client/client_procs.dm
- tgstation.dme
Title.
Makes it so that going into other stations (literally only other places using same code or forks) more... possible.
No.
:cl:
add: Added importing/exporting characters, they will be saved on your computer and you can take your character into other servers.
/:cl:
> Adds exporting/importing of character slots

- code/__HELPERS/mobs.dm
- code/modules/arousal/organs/breasts.dm
- code/modules/arousal/organs/butt.dm
- code/modules/arousal/organs/penis.dm
- code/modules/arousal/organs/testicles.dm
- code/modules/arousal/organs/vagina.dm
- code/modules/client/preferences.dm
- code/modules/client/preferences_savefile.dm
- modular_sand/code/datums/interactions/lewd_definitions.dm
- modular_sand/code/modules/arousal/genitals.dm
Title, you can start the day with your clothes "lazily put on".
Lewd?
No.
:cl:
qol: You can start the shift with your genitals accessible.
qol: Reorganized preferences to just fit stuff better than before.
/:cl:
> Preference for genital accessibility

- code/__SANDCODE/DEFINES/DNA.dm
- code/modules/arousal/genitals.dm
- code/modules/client/preferences.dm
- code/modules/mob/dead/new_player/preferences_setup.dm
Title.
No more guesswork, know how you look.
Yes, skyrat-tg, i don't feel like looking up where it was added.
:cl:
qol: You can check how you look when naked and aroused on the character prefs.
/:cl:
> Adds aroused preview to character prefs

- tgui/packages/tgui/interfaces/MobInteraction.tsx
Title.
Good and nice.
No.
:cl:
qol: The main window of the interaction ui no longer scrolls, only their contents.
qol: Moves the search bar, currently only working for interaction and genital searches.
/:cl:
> Some touch ups to the interaction ui

- code/controllers/subsystem/communications.dm
- code/game/machinery/computer/communications.dm
- tgui/packages/tgui/interfaces/CommunicationsConsole.js
Title.
No more paper spam.
No.
:cl:
add: Added a print button to the communication console's messages, disabled auto-print as well.
/:cl:
> Adds a print button to the communication console's messages

- code/game/objects/items/devices/PDA/PDA.dm
- code/modules/antagonists/devil/true_devil/_true_devil.dm
- code/modules/integrated_electronics/subtypes/smart.dm
- code/modules/mob/dead/observer/observer.dm
- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/living.dm
- code/modules/mob/living/living_mobility.dm
- code/modules/mob/living/silicon/ai/ai.dm
- code/modules/mob/living/silicon/pai/pai.dm
- code/modules/mob/living/silicon/robot/robot.dm
- code/modules/mob/living/simple_animal/simple_animal.dm
- code/modules/mob/mob.dm
- code/modules/modular_computers/computers/item/computer.dm
- code/modules/modular_computers/computers/item/tablet.dm
- code/modules/photography/camera/camera.dm
Title.
It usually sucks and i'm not going around to filter interactions allowing still for small hand devices.
No.
:cl:
tweak: tweaked a few things
qol: Machines can be interacted with while resting.
/:cl:
> Allows interaction with machines resting

- modular_sand/code/controllers/subsystem/interactions.dm
Title.
Info.
No.
:cl:
add: Interaction subsystem reports initialized interactions during init.
add: Interaction subsystem shows some info at the MC tab.
/:cl:
> Adds info about the subsystem during init and at the MC tab

- tgui/packages/tgui/interfaces/MobInteraction.tsx
Title.
Additional fix.
No.
:cl:
fix: required_from_user & target variables should check your requirements and the interaction's reqs more precisely.
/:cl:
> Adds some more checks to make sure you have what is required for the action

- code/modules/admin/verbs/selectequipment.dm
- code/modules/mob/dead/observer/observer.dm
- modular_sand/code/modules/mob/dead/observer/observer.dm
- tgui/packages/tgui/interfaces/SelectEquipment.js
Title.
Removes
Adds buttons to the select equipment menu
if target is ghost:
otherwise (hopefully human)
Better ui and gets rid of deprecated stuff
No.
:cl:
tweak: Adds some shiny buttons to admin select equipment.
del: Removes old quick spawn.
/:cl:
> Puts quick spawn in select equipment

- code/modules/integrated_electronics/core/assemblies.dm
- code/modules/integrated_electronics/subtypes/reagents.dm
- code/modules/integrated_electronics/subtypes/smart.dm
- modular_sand/code/modules/integrated_electronics/subtypes/input.dm
Title, those use action buttons.
Good for creativity and cool uses.
No.
:cl:
fix: Some of the old push refs on reagent circuits didn't work, they now do.
tweak: MMIs and pAIs circuits have been checked on.
add: Added quick button circuit! It uses actions buttons and are customizable.
/:cl:
> Adds a new circuit: quick button

- code/controllers/subsystem/processing/quirks.dm
- code/modules/client/preferences_savefile.dm
- modular_sand/code/controllers/subsystem/processing/quirks.dm
- modular_sand/code/modules/client/loadout/accessories.dm
Serious issues, misery.
People not using javascript to fuck admins is good.
No.
:cl:
fix: Sanitizes loadout items.
fix: Players get positive quirks removed until balanced when joining the game.
fix: Ring accessories have gotten their paths fixed, allowing them to appear once again in the accessory section of the loadout.
/:cl:
> Some fixes, check changelog

- code/modules/mob/living/living.dm
Title.
Stop fucking up my lavaland building!!!
No.
:cl:
tweak: Mobs that can push structures off the floor will no longer do so unless it blocks path to a target.
/:cl:
> Prevents mobs from pushing structures with no reason

- modular_sand/code/modules/mob/living/simple_animal/bot/hugbot.dm
Title. Turns out when JPS was introduced, the hugbot was still using some old code that is no longer supported, this just makes it use the code from the medbot (they're literally the same thing).
It's a fix, period.
No.
:cl:
fix: Fixed runtimes on hugbot.
/:cl:
> Fixes hugbots

- code/modules/client/preferences_savefile.dm
- modular_sand/code/datums/components/interaction_menu_granter.dm
- modular_sand/code/modules/client/preferences.dm
- modular_sand/code/modules/client/preferences_savefile.dm
- tgui/packages/tgui/interfaces/MobInteraction/tabs/InteractionsTab.tsx
Title, hard to miss in-game.
Keep your favorites in sight.
No.
:cl:
add: Added favorite interactions to the interaction menu, those persist between rounds and between characters.
/:cl:
> Adds favorites to interactions

- modular_sand/code/_onclick/hud/screen_objects.dm
Title, will redirect more mouse stuff to your own character.
Yes.
No.
:cl:
tweak: The healthdoll was made more responsive, for example, it will show screentips correctly.
/:cl:
> Makes health doll more responsive

- code/__SANDCODE/DEFINES/lewd.dm
- modular_sand/code/datums/interactions/interaction_datums/lewd/breasts.dm
- modular_sand/code/datums/interactions/interaction_datums/lewd/finger.dm
- modular_sand/code/datums/interactions/interaction_datums/lewd/handjob.dm
- modular_sand/code/datums/interactions/interaction_datums/lewd/self/breasts.dm
- modular_sand/code/datums/interactions/interaction_datums/lewd/self/finger.dm
- modular_sand/code/datums/interactions/interaction_datums/lewd/self/jack.dm
- tgui/packages/tgui/interfaces/MobInteraction/MainContent.tsx
- tgui/packages/tgui/interfaces/MobInteraction/tabs/InteractionsTab.tsx
Title. Moves the favorites toggles elsewhere.
Yes.
No.
:cl:
spellcheck: Rephrased the "can milk" interactions.
qol: Moves the position of favorites button for the interactions.
code: Makes a define for the "can milk" interaction description.
/:cl:
> Updates interaction favorites

- modular_sand/code/datums/interactions/_interaction.dm
Title.
Variety without having to do too much code.
No.
:cl:
code: Coders can now use a list of sounds for basic interactions.
/:cl:
> Allows simple interactions to have varied sounds

- code/datums/datacore.dm
- code/game/machinery/computer/security.dm
Solves some stuff and puts new stuff in, go check changelog.
Because less people doing html shit is good.
And fixes are always welcome.
No.
:cl:
add: Higher staff can now set titles for you on the manifest using the security console.
fix: Manifest will no longer have people with null jobs.
fix: High security vulnerability, you can no longer set your rank to be anything (see pr for info).
/:cl:
> Security console update

- code/modules/clothing/suits/_suits.dm
- code/modules/clothing/under/_under.dm
- code/modules/clothing/under/accessories.dm
- code/modules/mob/living/carbon/human/examine.dm
- modular_sand/code/modules/clothing/gloves/_gloves.dm
- modular_sand/code/modules/clothing/gloves/accessories.dm
There's so much wrong with accessory code in many ways, i want them to be made into elements/components sometime. That time is not now. But at least some of its issues are fixed here.
Fix.
:cl:
add: Rings attached to gloves show in people's examines like accessories.
refactor: Touched up a lot of broken accessory code, it needs more work in the future, but for now it's actually working.
/:cl:
> Fixing accessories :tm:

- modular_sand/code/datums/interactions/interaction_datums/lewd/frotting.dm
Adds 3 additional prompts to frotting that may be picked upon running the interaction.
Most interactions have several prompts that may come up, however this specific one had just one. Bad.
Nope.
:cl:
add: Frotting but awesome.
/:cl:
> Improves frotting

- code/datums/weather/weather_types/ash_storm.dm
- code/game/turfs/simulated/floor/plating/asteroid.dm
- code/modules/ruins/lavalandruin_code/elephantgraveyard.dm
Title.
Just a cool mechanic.
A port of [Storm weather related fixes](https://github.com/tgstation/tgstation/pull/76367)
:cl:
add: Ashstorms cover dug up holes in lavaland.
/:cl:
> Ashstorms refill dug holes

- code/__SANDCODE/DEFINES/lewd.dm
- modular_sand/code/controllers/subsystem/interactions.dm
- modular_sand/code/datums/components/interaction_menu_granter.dm
- modular_sand/code/datums/interactions/_interaction.dm
- modular_sand/code/datums/interactions/lewd_interactions.dm
- tgui/packages/tgui/interfaces/MobInteraction/InfoSection.tsx
- tgui/packages/tgui/interfaces/MobInteraction/MainContent.tsx
- tgui/packages/tgui/interfaces/MobInteraction/tabs/InteractionsTab.tsx
Title, but not only that, the players' component for interacting with others uses this processor to automatically interact with each other, to prevent spammy behavior they are not allowed to do an interaction they've set to automate.
Quality of life or whatever.
:cl:
qol: The official sandstorm automatic interactions is out, come and get it while it's still fresh.
/:cl:
> Makes the interactions subsystem tick
