Sandstorm-Station/Sandstorm-Station-13

code/game/machinery/spaceheater.dm

##About The Pull Request
space heaters can now be wrenched and unwrenched to remove bolts
space heaters now have 300% more laser powering and 200% more capacitor power
##Why It's Good For The Game
These things are worthless at dealing with most things above just 120c or below -30C
taking a long time and generaly only fixing slowly the 4~ tile area its around this fixes that
QoL to not have to make and un make a newly built space heater when you have to move it to cool the room
##Changelog
🆑
add: Space heaters can now be wrenched and unwrenched
balance: Space heaters drain less and can reach even hotter/colder temps faster!
/🆑

Buffs space heaters from Trillbyspaceclone#12241

---

code/game/objects/items/airlock_painter.dm
sandcode/code/game/objects/items/airlock_painter.dm
tgstation.dme

It's a radial menu for decal painter, doesn't lose any functionality, except for removing the old menu.
Preview? and the radial menu is cool.
:cl:
add: Added the radial menu.
del: Removes the old ui for radial menu, and most of the things that make it work.
/:cl:

Replaces decal painter menu with a radial menu

---

sandcode/code/datums/action.dm
sandcode/code/game/objects/items/devices/PDA/PDA.dm
tgstation.dme

* PDAs now have a toggle light action button, like other light sources
This has bugged me for years, so I'm assuming it bugs other people too.
:cl:
add: PDA toggle light action button
/:cl:
This ports one of https://github.com/tgstation/tgstation/pull/48336's changes.

PDA toggle light action button port

---

code/controllers/subsystem/statpanel.dm
code/controllers/subsystem/time_track.dm

Line breaking.
`"Server Time: [time2text(world.timeofday, "YYYY-MM-DD hh:mm:ss")]\n\nRound Time: [DisplayTimeText(world.time - SSticker.round_start_time, 1)] \n\nStation Time: [STATION_TIME_TIMESTAMP("hh:mm:ss", world.time)]\n\n[time_dilation_text]"`, despite the "\n"s will be displayed in a single line (also repeats some information that's already on the stat panel), this solves it.
:cl:
tweak: Time info on the stat panel is no longer messy.
/:cl:

Breaks lines... with a crowbar

---

code/modules/mob/living/simple_animal/hostile/headcrab.dm

That's pretty much it.
You could actually return to human form before without the button with a statpanel verb, the problem is, THE STATPANEL "CHANGELING" TAB DOES NOT EXIST ANYMORE.
If there is questioning what said button is:
:cl:
fix: The "Human Form" button will actually appear after becoming a monkey from biting a corpse as a headslug.
/:cl:

Changelings can properly return to their form now

---

html/changelogs/SandPoot brute force copy 2.yml
sandcode/code/modules/shuttle/spaceship_navigation_beacon.dm

Title.
On the fix prior to this, shuttles could not move anywhere without a z-lock allowing then, thus this will make so that built beacons will add their Z to all custom shuttle computers.
:cl:
fix: Finally 100% fixes beacons, you can now build beacons and go to that Z-level on your custom shuttle (or whiteship i guess).
/:cl:

More spaceship beacon fixes

---

code/game/turfs/simulated/floor/plating.dm
sandcode/code/game/turfs/simulated/floor/plating.dm
tgstation.dme

Allows you to place plating instead of a regular tile on asteroid tiles and platings on the station can be removed, revealing a hole to space.
This is important, and helps with some stuff. (It's hard to build a base on lavaland when the floor there is basically a scrubber on siphon and sometimes floors need to be completely removed!)
A bit, uses some stuff from https://github.com/Lumos-SS13/Lumos/commit/b46f2d07532f7d3f7cd2a3f8e49221d2e539f9c9 and https://github.com/ParadiseSS13/Paradise/commit/fddff1049b970872dd539eb5b9ebc6a434b8e301(paradise is a shrug, this is probably very old).
:cl:
add: Platings can be removed from the floor (currently only certain ones), just examine it to know if you can or not, and how to.
tweak: Trying to place a tile on an asteroid turf, such as lavaland's, …

Plating changes

---

code/game/objects/items/airlock_painter.dm
sandcode/code/game/objects/items/airlock_painter.dm

Title and also increases the radius of the menu that's full of options, the sprites were not so cozy like that.
Fix good.
No
:cl:
tweak: The radial type selection for the decal painter now has a bigger radius, so that no sprites go over each other.
fix: Decal painter previews now appear the right way.
/:cl:

Fixes decal painter radial previews

---

code/game/machinery/announcement_system.dm
code/game/machinery/cryopod.dm

Title.
Hart's fix for the cryopods absolutely deprecates `on_store`, this makes sure the "cryo tele" still works and shows the proper message.
No.
:cl:
fix: The teleporter no longer "cryos" you (it will display the correct message on radio).
/:cl:

Telecryo fix

---

sandcode/code/game/objects/items/storage/bags.dm
tgstation.dme

Adds dropper and stabilized slime extracts
Efficiency in xenobio, and storage for anyone who uses stabilized cores
Nope
:cl:
add: Droppers to biobag white list
add: Stabilized slime cores to biobags white list
/:cl:

Adds new items to biobag whitelist

---

sandcode/code/game/objects/items/storage/boxes.dm
tgstation.dme

title
stealing is bad? maybe.
Yes, https://github.com/Citadel-Station-13/Citadel-Station-13/pull/13868.
:cl: Hatterhat
add: Apparently someone started shoving golem vendor boards into every liberator's legacy. How odd!
/:cl:

Puts a golem vendor board in every liberators legacy

---

code/controllers/configuration/entries/game_options.dm
code/datums/brain_damage/hypnosis.dm
code/datums/brain_damage/severe.dm
code/datums/status_effects/debuffs.dm
config/sandstorm/config.txt

Fix dangling parentheses breaking regex in hypnotic stupor
Added optional limits to how often a hypnotic stupor can apply a trance
Fixes dangling parentheses breaking regex in hypnosis and establishes a minimum duration that a hypnosis from the quirk Hypnotic Stupor (via Trance status effect) must persist.
The bugfix fixes runtime error spam (every tick in Life()) and allows brain traumas to actually process (there must not be a null brain trauma). The tweak to hypnotic stupor is because despite there only being a 1% chance every tick to trigger a Trance, it still can make hypnosis rapidly change making it difficult to roleplay into that command.
Nope.
:cl:
tweak: Changed Hypnotic Stupor quirk to only reapply a trance after a minimum amount of time from a previous hypnosis
fix: Hypnosis …

Hypnotic stupor tweaks and Hypnosis regex fix

---

code/modules/flufftext/Hallucination.dm

This PR adds a nullcheck for a likely very rare edgecase runtime error the server may experience when running a chat hallucination but the client's reference is lost during the 30 deciseconds the script is asleep.
Improves server stability (wasn't a crash, but likely would prevent any hallucinations from ever running from then on)
Nope.
:cl:
fix: Added another nullcheck for a rare edge case runtime exception for a lost reference during a sleep step in Hallucination.dm
/:cl:

Fix? for nullref during hallucination sleep

---

code/controllers/subsystem/ticker.dm
config/sandstorm/config.txt
modular_sand/code/controllers/configuration/entries/sandstorm.dm
modular_sand/code/controllers/subsystem/ticker.dm
tgstation.dme

Title.
Locks gamemodes to a default set by the server operator, of course it can still be turned off or admins change it.
Also if any other gamemode fails starting up, it will default to extended.
Now it is indeed extended forever.
No.
:cl:
fix: No more infinite unable to start rounds, if it happens the game should force to start extended.
config: Voting can now be disabled to allow for a single gamemode type.
/:cl:

Force gamemode config

---

modular_sand/code/game/machinery/cryptominers.dm
modular_sand/code/modules/mining/machine_bluespaceminer.dm

Title, having better stock parts on the bluespace miner increases generation and if all the parts are alien tier, unlocks bluespace generation aswell.
PLEASE NO MORE USELESS UPGRADING.
No.
:cl:
tweak: Stock part tiers now matter for the bluespace miner, PRODUCE MORE!
tweak: Cryptominers "small screen" can only be looked at up close.
/:cl:

Bluespace miner now affected by stock part tier

---

modular_sand/code/modules/mob/dead/new_player/sprite_accessories/body_markings.dm
modular_sand/code/modules/mob/dead/new_player/sprite_accessories/ears.dm

Title.
The path being wrong results in stuff like not being choosable in several places, for example, slime body alteration.
No.
:cl:
fix: Fixes incorrect pathing for sprite accessories.
/:cl:

Fixes some sprite accesory paths

---

modular_sand/code/modules/clothing/underwear/_underwear.dm

Should prevent awful direction sprites while on the floor, but seriously, if only someone could provide underwear sprites (and that means for all of them).
Looks nicer and you won't have the chance of losing your underwear because it's current state has too few pixels.
No.
:cl:
code: Forces underwear item sprite to face south.
/:cl:

Prevents underwear from using direction sprites on the floor

---

code/game/objects/items/devices/dogborg_sleeper.dm
code/modules/mob/living/silicon/robot/robot_modules.dm
modular_sand/code/game/objects/items/devices/dogborg_sleeper.dm
tgstation.dme

Title, also makes so _nv is not used thus not breaking belly sprites, only the default medihound has it, shouldn't force the others to try.
Makes code nicer and adds something nice to garbage sweepers.
No.
:cl:
add: Re-adds janitor module garbage processor.
fix: Borgs shouldn't be lacking belly sprites, when holding something inside.
code: Borg sleepers use better code.
/:cl:

Makes borg sleepers use a nicer code and revives janitor module's processor

---

code/game/objects/structures/watercloset.dm
tgui/packages/tgui/interfaces/PaperSheet.js

fixes some errors, port of our https://github.com/SPLURT-Station/S.P.L.U.R.T-Station-13/pull/80
Removed one of the runtimes for PaperSheets - where a null text was runtiming, added a check for it.
Removed one of the runtimes for the showers for when a null object is placed under the showers somehow. (added a check for it)
i hate lag
kinda...?
:cl:
fix: now it checks if a paper's content is null rather than runtiming
fix: fixes shower null objects
/:cl:

fixes some runtimes (again)

---

modular_sand/code/datums/interactions/interaction_interface.dm
tgui/packages/tgui/interfaces/MobInteraction.js

Title.
The window from genital picking was awful, and the other tab felt right to have those.
No.
:cl:
tweak: Set-Gender for borgs was moved to Robot Commands tab on the statpanel.
tweak: Beautified some ui on the interaction menu.
/:cl:

Modifies interaction prefs on the interaction menu

---

code/__HELPERS/mobs.dm
code/__HELPERS/roundend.dm
code/modules/admin/admin_verbs.dm
modular_sand/code/modules/admin/verbs/randomverbs.dm
tgstation.dme

Title.
Helpful.
No.
:cl:
add: Admins have a special shiny button to end the round ic.
fix: No longer calling CHECK_TICKs for no reason.
config: If reveal everything is false, ghosts can no longer speak to the living when the round ends.
/:cl:

Adds a command for admins to easily end the shift (calls shuttle) + misc stuff

---

modular_sand/code/datums/interactions/lewd/lewd_interactions.dm

For some reason require_target_num_feet was set to count the number of feet the user had instead of the target's. This pr makes it right.
You don't need feed to receive a feetjob from someone else, they do!
no
:cl:
fix: Lewd verbs will actually count for the target's feet when needed
/:cl:

fixes a small error in the lewd verbs

---

modular_sand/code/modules/clothing/underwear/shirts.dm

The way tops were declared you were forced to use them in the normal underwear slot. This makes them use the shirt one as I guess it was intended to
Now you can wear a top + undies instead of having to choose either
No
:cl:
bugfix: Tops will now use the shirt slot
/:cl:

Fixes tops

---

.github/workflows/compile_changelogs.yml

The way it currently is it will never activate for a pr. You have to push directly to master and make sure your push edits the folders mentioned in the workflow run. Since the Makce changelogs workflow skips every other workflow when it's pushed, it basically made compilation never run. With this edit, it will run whenever the Make changelogs workflow is done running, which works both for pull requests and for pushing directly to master. Essentially making it work as it was intended
Compile changelogs is currently ultra-borked
:cl:
code: Fixed the Compile changelogs workflow so it actually runs and is also more responsive as it was intended
/:cl:

Makes the workflow actually work as it was intended

---

code/__HELPERS/reagents.dm

For some reason the way reagent choosing was coded in such way that when introducing a full right path of a reagent this isn't turned ever into an actual path. This makes it so that the game attempts to pass a string as path and therefore not add the reagent at all. Funnily enough this makes it so the only way to add reagents through vv is to put a wrong/incomplete path and then choosing the one you want from the list.
This pr fixes the bug, though.
I don't copy the full paths directly from the code for nothing you know?
No
:cl:
fix: fixes the bug where reagents won't add through view variables if you enter their full path
/:cl:

fixes vv reagent choosing

---

code/game/objects/items/stacks/sheets/mineral.dm
code/game/objects/structures/beds_chairs/chair.dm

What title says, takes 2 titanium to make one, and when you deconstruct a shuttle seat it drops 2 titanium
They look really cool and if you want to simulate the shuttle experience with seats you should be able to
Yes, https://github.com/tgstation/tgstation/pull/50455.
:cl:
add: You can now make shuttle seats with titanium.
/:cl:

You can now make shuttle seats with titanium

---

_maps/map_files/Deltastation/DeltaStation2.dmm
modular_sand/code/datums/interactions/interaction_interface.dm
tgui/packages/tgui/interfaces/MobInteraction.tsx

The verbs for handling genitals still suck, this does something so you don't have to touch them.
It's a nice little feature.
No.
:cl:
tweak: Interaction's tabs are now centered and fluid, getting a better look overrall.
qol: Arousal can now be toggled on the interaction ui, check the renamed tab "genital options".
/:cl:

Adds an arousal button to the interaction ui (also does some ui "niceing")

---

modular_sand/code/modules/research/techweb/nodes/all_nodes.dm

Changes the Advanced Toolset Implant techweb entry to also require Alien Engineering and Cybernetic Implants. This prevents obtaining alien tool implants before researching tool implants or alien tools.
Prevents sequence breaking the techweb using alien technologies.
No.
:cl:
fix: Fixed techweb sequence break for Advanced Toolset Implant
/:cl:

Fix Adv Toolset sequence break

---

code/modules/mob/dead/new_player/new_player.dm

Fixes a redundant display of job slots on the latejoin panel.
Caused by https://github.com/Citadel-Station-13/Citadel-Station-13/pull/15919
(This is what is being fixed)
Code should function properly.
No.
:cl:
fix: Fixed the late-join panel showing job slots twice
/:cl:

Fix late-join panel job slot numbers

---

modular_sand/code/modules/research/techweb/nodes/all_nodes.dm

Moves the Autodoc from Advanced Surgery to Advanced Surgery Tools, since it cannot be constructed without the items from that node. Specifically, the _searing tool_ and _mechanical pinches_ are both required, but are unavailable without further research.
Prevents unlocking a machine before it can be constructed, which can be a source of confusion.
No.
:cl:
tweak: Moved Autodoc techweb entry from Advanced Surgery to Advanced Surgery Tools
/:cl:

Minor techweb fix for autodoc

---

modular_sand/code/game/objects/items/circuitboards/machine_circuitboards.dm
modular_sand/code/modules/research/techweb/nodes/bluespace_nodes.dm

Updates bluespace miners construction and techweb requirements. Made at the request of user _SandPoot_.
- Added construction requirement of activated bluespace core
- Added techweb requirement for Anomaly Research
- Removed construction requirement of bluespace crystals
Bluespace miners can be used to trivialize the game's resource gathering and management systems early into a round. Increasing the requirement, without completely removing it, serves to delay the time before station resources are effectively infinite.
No.
:cl:
tweak: Bluespace mining research is now behind Anomaly Research
balance: Bluespace miners now require a bluespace anomaly core
/:cl:

Require bluespace core for BSMs

---

code/datums/brain_damage/severe.dm

Doll with monophobia trauma dont die in someones belly from heart attack (same with just blinded doll (need someone in 1 tile radius)
Die in someone just with reason "alone" and same thing while you blinded and someone hugs you, but you dies from being "alone" and other other other rp breaking moments.
:cl: Winter Schock
fix: Doll with monophobia dont get stress in someone vore belly 
fix: Blind doll with monophobia dont get stress while someone in 1 tile range 
/:cl:

Monophobia vore and blind fix

---

code/__SANDCODE/DEFINES/traits.dm
code/game/machinery/computer/cloning.dm
code/modules/mob/living/brain/brain_item.dm
modular_sand/code/datums/traits/negative.dm
modular_sand/code/game/machinery/computer/cloning.dm
tgstation.dme

Ports the do-not-clone quirk from SPLURT. Like the original; This change is not modular.
The following changes are made from the original:
- Added a fix for cloning heads and brains
- Removed flavor text implications that the order was voluntary
- Quirk renamed from `DNC` to `DNC Order`
- Trait renamed from `TRAIT_NO_CLONE` to `TRAIT_DNC_ORDER`
This port made at the request of user SandPoot.
Allows crew to reject the cloning system for mechanical or lore reasons, while also being rewarded with quirk points for doing so.
Yes: Ported from SPLURT Station 13.
The original commit can be found here: https://github.com/SPLURT-Station/S.P.L.U.R.T-Station-13/commit/561831bde308290a17fbd54774e57c83b8d2934a
:cl:
add: Added quirk: DNC Order
/:cl:

[PORT] New quirk: DNC Order

---

code/__SANDCODE/DEFINES/traits.dm
modular_sand/code/datums/traits/neutral.dm
modular_sand/code/modules/mob/living/carbon/human/species_types/lizardpeople.dm

This PR ports quirks related to the animal breeding cycle from the downstream server SPLURT. The quirks add examine flavor text, and the ability to see said flavor text. No gameplay effects currently exist.
Actions were requested by user SandPoot.
Yes, ported from [SPLURT Station 13](https://github.com/SPLURT-Station/S.P.L.U.R.T-Station-13). Originally added to the game in PR https://github.com/SPLURT-Station/S.P.L.U.R.T-Station-13/pull/20 by GitHub [user NullFag](https://github.com/NullFag).
:cl:
add: Added quirk Estrous Detection
add: Added quirk In Estrous
tweak: Ashwalkers now spawn with the Estrous Detection quirk
tweak: Ashwalkers will now gain the In Estrous quirk during some rounds
/:cl:

Port estrous quirks from SPLURT

---

config/sandstorm/balance.txt
modular_sand/code/controllers/configuration/entries/sandstorm_balance.dm
modular_sand/code/game/machinery/computer/arcade/tetris.dm

This PR updates the T.E.T.R.I.S. arcade machine with the following attributes
- Adds configuration values to the Sandstorm balance config
- - Allow generating science points
- - Reward divisor
- - Maximum prizes
- - Maximum score
- - Maximum research points
- - Threshold to alert admins
- - Cooldown time between vending
- Adds new messages for vending no prizes
- Adds a cooldown between dispensing rewards
- Adds an admin alert when exceeding the score threshold
- Grants science points if the player's ID has science access
- Limits maximum score
- Limits maximum prizes
This will do the following:
- Add additional configuration
- Add a new method for scientists to earn research points
- Reduce cheating potential
No.
:cl:
balance: T.E.T.R.I.S. arcade machine now generates research points if …

TETRIS machine rewards refactor

---

modular_sand/code/modules/uplink/uplink_items.dm

Marks the 357 speed loader as non-illegal-tech to prevent an exploit with the research techweb. As it was made craftable in a modular edit, the item can now be made by any normal crew member and used to immediately unlock the Illegal Technology techweb node.
Fixes an exploit that allowed sequence breaking a techweb node.
No.
:cl:
fix: Fixed techweb exploit with 357 speed loader
/:cl:

357 Speed Loader research fix

---

modular_sand/code/modules/clothing/under/miscellaneous.dm
tgstation.dme

Sets the gear harness to non-covering by default, and removes the ability to adjust it. The toggle function has been updated to prevent false feedback. Users can still use the visibility settings to conceal associated body regions.
This item is designed to facilitate playing as a naked character while being able to handle items, but acts as normal clothing by default. In addition, it is an invisible item that does not appear on the mob, and has no way of covering them.
No.
:cl:
tweak: The Gear Harness is now non-covering
/:cl:

Make Gear Harness non-covering

---

modular_sand/code/datums/traits/neutral.dm

This commit does the following for In Estrous examine text:
- Adds English list support
- Adds support for synthetic species
- Removes check for Vagina organ
- Updates text to prevent double "and"
This will accomplish the following:
- Create cleaner and more expandable code
- Prevent checking an organ that doesn't produce hormones
- Add more flavor text for synthetic species
No.
:cl:
add: Added Synthetic species flavor text for In Estrous
tweak: In Estrous no longer requires both female organs
code: In Estrous examine text uses English lists
/:cl:

Use english list for In Estrous examine text

---

modular_sand/code/modules/research/machinery/departmental_protolathe.dm
modular_sand/code/modules/research/machinery/departmental_techfab.dm

Changes the production machinery access requirement for cargo from `ACCESS_CARGO` to `ACCESS_MAILSORTING` to fix an issue that prevented Shaft Miners from using the machine.
Allows Shaft Miners to use the Cargo protolathe.
No.
:cl:
fix: Fixed Cargo protolathe access (MAILSORTING instead of CARGO)
/:cl:

Fix cargo production access

---

code/__SANDCODE/DEFINES/access.dm
modular_sand/code/modules/mob/mob.dm
modular_sand/code/modules/research/machinery/_production.dm
tgstation.dme

This PR allows crew with `ACCESS_MINERAL_STOREROOM` access to use production machinery in 'mineral only' mode when normal access isn't found. This allows changing screens, synchronizing, and ejecting materials.
In addition:
- Adds new return types for access types
- Adds a separate function for topic access checks
- Adds new feedback for topic access denial
- Changes the main access check to use `allowed` proc
- Moves feedback messages to the production machine
Allows for engineers and other crew with material access to continue accessing resources from any production machinery on the station.
No.
:cl:
add: Added better feedback for production machinery topic access denial
tweak: Production machinery access checks now work for all mobs
balance: Production machinery can now be used in …

Allow material access from protolathes

---

modular_sand/code/datums/components/interaction_menu_granter.dm
tgui/packages/tgui/interfaces/MobInteraction.tsx

You require estrous detection to see theirs.
Info.
No.
:cl:
qol: Lust levels can be seen in the interaction menu (you can only see theirs if you have estrous detection).
/:cl:

Allows for seeing lust levels inside the Interaction menu

---

modular_sand/code/modules/research/rdconsole.dm
tgstation.dme

This PR reverts the change causing R&D consoles to be locked by default upon creation, as it had unintended consequences. This restores the exploit of disassembling locked consoles to bypass locks.
Console locks were causing unintended issues, including those reported for ghost roles. The benefit of this change did not outweigh the issues caused.
No.
:cl:
tweak: Reverted R&D consoles locking by default
/:cl:

Revert RnD console locks

---

modular_sand/code/modules/jobs/job_types/_job_alt_titles.dm

Adds new, Roman Republic themed alt-titles for the Captain, Head of Security, and the Chaplain. 
This pull request ports the Senator alt title for the captain from Splurt, and also adds a "Consul" Alt title. The HoS gets a new title, "Praetor", and the chap gets "Pontiff". Roma Invitca, even in space!
Given that Splurt has a senator alt-title and has a bunch of meme alt titles in general, what's wrong with a bit of harmless RP? (Yes, I get we are HRP, but still)
Partially
:cl: Arrhythmia_V
Code/Add: Alt Titles
/:cl:

Space Romans

---

modular_sand/code/modules/mob/mob.dm
modular_sand/code/modules/vehicles/mecha/mech_fabricator.dm
tgstation.dme

This commit updates the production machinery restrictions to include mech fabricators. Old production check code has been updated for use with generic machines, and some checks have been moved. Alternative `maint` and `offstation` variants have had their access requirements removed to compensate.
Acts as a follow-up to: https://github.com/Sandstorm-Station/Sandstorm-Station-13/pull/303
As with the original PR, this will also reduce cases of unauthorized ("grey tiding") production use for **standard** mech fabricators.
No.
:cl:
balance: Mech fabricators now use their access restrictions
balance: Removed access requirements for maintenance and off-station mech fabricators
/:cl:

Add robotics production restrictions

---

code/datums/elements/mob_holder.dm
modular_sand/code/datums/elements/holder_micro.dm

People still have no idea how to pick up people, they probably still won't because majority of those smartasses play with it off, at least i get a reason to laugh at their faces more.
Obviously not.
:cl:
tweak: How to grab small people and certain simple mobs is now explained on the screen hints, if you have them verbose that is.
code: Applied COMPARE_SIZES macro to the micro code.
/:cl:

Adds hints to picking up people/certain simple mobs

---

code/game/objects/items.dm

Title.
The pick up verb has different checks for picking up stuff than when you just click the thing. This just makes the verb click for you instead.
So you can now pick up stuff while lying down using the right click menu!
:cl:
fix: Made the pick up verb act as a click, removing dumb checks that click normally would not have.
/:cl:

Makes the pick up verb less shit

---

modular_sand/code/datums/components/interaction_menu_granter.dm
modular_sand/code/datums/interactions/interaction_datums/interaction_definitions.dm
tgui/packages/tgui/interfaces/MobInteraction.tsx

Title, also adjust some interactions to make more sense.
Helpful.
No.
:cl:
qol: Buttons for interactions don't appear on interaction menu if your mob type (or theirs) is blacklist, preventing you from losing time with "Y DOES NOT WORK".
tweak: Changed some interaction requirements to make more sense.
/:cl:

Prevents buttons from showing on interaction menu if your mob type is blacklisted

---

code/modules/unit_tests/interactions.dm
modular_sand/code/controllers/subsystem/interactions.dm
modular_sand/code/datums/components/interaction_menu_granter.dm
modular_sand/code/datums/interactions/_interaction.dm
modular_sand/code/datums/interactions/interaction_datums/lewd/slap.dm
modular_sand/code/datums/interactions/lewd_interactions.dm
tgstation.dme
tgui/packages/tgui/interfaces/MobInteraction.tsx

Title, adds unit tests and some other stuff.
Fixes.
No.
:cl:
fix: Interactions that allow both exposed and unexposed can be done once again.
refactor: "Slap their ass" has been moved off of /datum/interaction into its own interaction, using basetypes for anything is now forbidden.
code: There are now unit tests for creating interactions incorrectly.
qol: Max distance check has been flipped to make more sense.
/:cl:

Fixes interactions that can be done if requirement allows exposed or unexposed

---

code/game/say.dm
strings/tips.txt

This stuff has been cramping 100% heavy roleplay style for too long.
Somehow, the way maptext is formatted* seems to break tag ends found around a line break. This usually happens when a space with width is found by the end of the line, and I don't recall ever encountering the issue otherwise.
Apparently, I've also found out that concatenating two spaces, regardless of width, seems to fix the issue just fine, and that brings in the solution to this whole pedantic problem: a zero-width space at the end of the closing tag.
*That's handled behind the curtains by the engine, so I can only throw wild guesses to why it happens.
Oh, by the by, I've also changed the tip about text modifiers I've made over a year ago. It was too confusing to read.
Comparison between before and after, and how it …

Fixes text effects for runechat.

---

code/modules/client/preferences.dm
code/modules/client/preferences_savefile.dm
modular_sand/code/datums/components/interaction_menu_granter.dm
modular_sand/code/datums/interactions/lewd_definitions.dm
modular_sand/code/modules/client/preferences_savefile.dm
modular_sand/code/modules/client/preferences_toggles.dm
tgstation.dme

Title.
It's a good idea to have preferences to be about enabling something, and not disabling something.
No.
:cl:
add: Top-left menu now has lewd sounds toggle.
tweak: The preference for lewd sounds is now about activating them, not muting. (your preferences have been automatically flipped to account for this)
tweak: Long strip menu is meant to be default on for sandstorm, and so it has been set so.
/:cl:

Makes lewd sounds appear on the top-left settings menu and defaults long strip menu
